From: Test <from@test.com>
Message-ID: <701141022.4.1458334846928@Marek-vostro>
Subject: subject
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_Part_3_1845904670.1458334846909"
X-Custom-Header: CustomValue

------=_Part_3_1845904670.1458334846909
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

Body's text (text)
------=_Part_3_1845904670.1458334846909
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Body's text <strong>(html)</strong></p>
------=_Part_3_1845904670.1458334846909--