Date: Fri, 7 Mar 2014 02:13:39 +0100 (CET)
From: test@test.com
To: somebody@somewhere.com
Message-ID: <403312604.0.1394154819963.JavaMail.myHost@myMachine>
Subject: JavaMail test at Fri Mar 07 02:13:39 CET 2014
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

Dear Visitor,

A few months ago I discovered great javaMail extension.
Visit https://github.com/m-szalik/javamail/wiki for more details.

    Kind Regards
    Developer